### ISSUE TITLE
2.0 timeline

### ISSUE THREAD

**Issue by jjl** [joken-elixir/joken#201]
Hi,

Do you have an indication of how long it'll take to stabilise Joken 2? Is there anything I can do to help move it forward?

Cheers,
James

**Comment by victorolinasc** [comment]
Hi @jjl 

There is, currently, only 1 bug with hooks. I'll try to take a look into it this week. Cannot guarantee you a timeline but I think this weekend we are good to go 2.0.0 final.

There will probably be a 2.1.0 with pluggable crypto (using built-in algorithms) in the near future but that won't change the public API. 

We will probably move this to a github organization so that we can group projects better: there is joken_jwks now and with the pluggable algorithms plus hooks there might be more projects joining the party (like a logging hook, a plug hook etc).

Regards,

**Comment by victorolinasc** [comment]
Timeline is clearer now. Please read the last RC release notes: https://github.com/joken-elixir/joken/releases/tag/v2.0.0-rc3

I'll close this now. If we the plan fails, please re-open the issue!

Thanks once again and cheers!
