### ISSUE TITLE
validation fails when aud is nil

### ISSUE THREAD

**Issue by mcfiredrill** [joken-elixir/joken#225]
The library seems to fail validation if the aud claim is not present.
```elixir
iex(8)> {:ok, claims} = Chat.JwtAuthToken.verify_and_validate(token)
[debug] Claim %{"aud" => nil} did not pass validation.

Current time: 1555402843

** (MatchError) no match of right hand side value: {:error, [message: "Invalid token", claim: "aud", claim_val: nil]}
    (stdlib) erl_eval.erl:453: :erl_eval.expr/5
    (iex) lib/iex/evaluator.ex:257: IEx.Evaluator.handle_eval/5
    (iex) lib/iex/evaluator.ex:237: IEx.Evaluator.do_eval/3
    (iex) lib/iex/evaluator.ex:215: IEx.Evaluator.eval/3
    (iex) lib/iex/evaluator.ex:103: IEx.Evaluator.loop/1
    (iex) lib/iex/evaluator.ex:27: IEx.Evaluator.init/4
iex(8)> 
```

I'm still really new to JWTs so I'm not really sure if this is intended behavior or not.
I was able to verify my token with a different elixir library:
https://github.com/garyf/json_web_token_ex

**Comment by victorolinasc** [comment]
This is because `aud` is a default claim. You can customize your claim validation like this:

```elixir
defmodule MyToken do
  use Joken.Config
  def token_config do
    default_claims(skip: [:aud])
  end
end
```

Also note that a "null" claim and an absent claim are different things. A nil claim (like the one you used in your example) is a claim that IS present in your token with value `null` or maybe an empty string. This is probably a serious thing on your token generation side of things.

Joken would not fail validation if the claim was absent. 

Hopefully this helps! If that is ok to you I'll close this issue.

**Comment by mcfiredrill** [comment]
> Joken would not fail validation if the claim was absent.

By absent you mean, instead of being null or empty string the key for the value is not present at all, right?

**Comment by victorolinasc** [comment]
Exactly!

**Comment by victorolinasc** [comment]
I am closing this here. Follow discussion on #224
