### ISSUE TITLE
Version bump

### ISSUE THREAD

**Issue by hez** [joken-elixir/joken#322]
It would be nice to have a version bump to pull in the latest jose which includes support for OTP24, there have been deprecations in :crypto which prevent the version of jose in 2.3.0 from compiling on OTP24.

**Comment by victorolinasc** [comment]
I totally agree! Haven't done that yet because there is actually many incompatibilities still in JOSE with OTP 24. Currently you can have a warning-less working version in OTP23 but OTP24 is not yet working across all cases in JOSE.

This was just merged: https://github.com/potatosalad/erlang-jose/pull/118 but it seems there is no new version of JOSE with that in. Also, some tests are still breaking.

I believe that in a near future we will have a new version of JOSE and I will update joken accordingly. Also, you can explicetely declare jose with override (that is what I do with OTP 23):

``` elixir
{:jose, "~> 1.11.1", override: true}
```

Beware with the 1.11.0 version! It is completely broken but it is not deprecated on hex.

I will leave this open and track the state of JOSE. I tried to help there with some PRs but there are still things to be done it seems.

**Comment by victorolinasc** [comment]
Adding related issue opened on JOSE: https://github.com/potatosalad/erlang-jose/issues/119

**Comment by victorolinasc** [comment]
Fixed with new version 2.4.0
